# Generated by Django 4.0.2 on 2022-07-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='imagen',
            field=models.ImageField(null=True, upload_to='PF/media'),
        ),
    ]
