# Generated by Django 4.0.2 on 2022-07-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_page_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='imagen',
            field=models.ImageField(null=True, upload_to='PF/media'),
        ),
    ]
