# Generated by Django 4.0.2 on 2022-07-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='imagen',
        ),
    ]
