# Generated by Django 4.0.2 on 2022-07-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_page_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='photo',
            field=models.ImageField(null=True, upload_to='PD/media'),
        ),
    ]
