# Generated by Django 4.0.5 on 2022-07-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='photo',
        ),
    ]
